name: google
version: 1.0.0
description: Google Plugin for PolymorphicBot
dependencies:
  http: '>=0.11.1+1 <0.12.0'
  irc: '>=1.4.5 <1.4.7'
  plugins: any
plugin:
  commands:
    "google":
      description: "Search Google"
      usage: "google <query>"
    "shorten":
      description: "Shortens URLs with goo.gl"
      usage: "shorten <url>"
